name: Sync with upstream (preserve .github)

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/LadybirdBrowser/ladybird.git
          git fetch upstream

      - name: Sync with upstream but skip .github
        run: |
          # Make sure we’re on master
          git checkout master

          # Create a temp worktree to stage changes
          git fetch upstream master
          git checkout upstream/master -- .  # Bring in everything

          # Restore our own .github folder
          git restore --source=HEAD --staged --worktree .github || true
          git restore --staged --worktree -- README.md  # Keeps README as-is
          
          # Commit the sync
          git add -A
          git commit -m "Sync with upstream (excluding .github)" || echo "No changes to commit"
          git push origin master
