name: Sync with upstream (preserve .github and README.md)

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/LadybirdBrowser/ladybird.git
          git fetch upstream master

      - name: Sync with upstream (preserve .github and README.md)
        run: |
          # Check out upstream files into working directory
          git checkout upstream/master -- .
          
          # Restore our files that we want to preserve
          git restore --source=HEAD --staged --worktree .github README.md
          
          # Commit and push
          git add -A
          git commit -m "Sync with upstream (excluding .github and README.md)" || echo "No changes to commit"
          git push origin master
